### ISSUE TITLE
.DS_STORE を .gitignore に書きませんか

### ISSUE THREAD

**Issue by t4t5u0** [ryusuke920/tex#8]
.gitignore に .DS_STORE を書く
```
git rm --cached .
```
する

**Comment by ryusuke920** [comment]
あれ、これでいいのかな？いまいちわからない
.ds_storeって何なの？.gitignoreの存在もいまいちわかってないー、、
.DS_STOREがtexの階層と微分方程式の階層の両方にあるんだけどどうすればいいんや？？

**Comment by t4t5u0** [comment]
.DS_Store だったわ

**Comment by ryusuke920** [comment]
書き換えたけど
git rm --cached .
やっても何もおこらない、、

**Comment by ryusuke920** [comment]
あ、できた
git rm -r --cached .
したらできた
何が起きたのかはよくわからなかったけど。
